##############################################################################
# Variables
##############################################################################
TOP=../..

-include $(TOP)/Makefile.config

LIBNAME=lib

SRC=gui.ml

INCLUDEDIRS=$(TOP)/commons $(TOP)/external/lablgtk2

OCAMLMKLIB=ocamlc -a
OCAMLMKLIBOPT=ocamlopt -a

-include $(TOP)/commons/Makefile.common
