# -*- makefile -*-
##############################################################################
# Prelude 
##############################################################################

# This file assumes the "includer" has set the variables below and then done
# a 'include Makefile.common':
#  - TOP
#  - SRC
#  - INCLUDEDIRS

# For literate programming, it assumes more variables:
#  - SRCNW
#  - TEXMAIN
#  - TEX

# For (un)installation, it assumes:
#  - LIBNAME, OPAMPKG

# this can set extra flags like -bin-annot that we want to be everywhere
-include $(TOP)/Makefile.config
# this can set extra flags like -warn-error
-include $(TOP)/Makefile.user

##############################################################################
# Generic variables
##############################################################################

INCLUDES?=$(INCLUDEDIRS:%=-I %) $(SYSINCLUDES)

OBJS?=    $(SRC:.ml=.cmo)
OPTOBJS?= $(SRC:.ml=.cmx)


##############################################################################
# Generic ocaml variables
##############################################################################

#dont use -custom, it makes the bytecode unportable.

#-4  allow | _ patterns in match
#-6  allow omit labels
#-29 alow multiline strings
#-45 allow shadowing open (TODO: fix them though)
#-41 allow ambiguous constructor in 2 opned modules (TODO: fix them though)
#-44 allow shadow module identifier (TODO: fix them)
#-48 allow eliminating optional arguments, unclear how to fix without wide
#    changes
WARNING_FLAGS?=-w +A-4-6-29-41-44-45-48

OCAMLCFLAGS=-g -thread -dtypes $(WARNING_FLAGS) $(OCAMLCFLAGS_EXTRA) 

# This flag is also used in subdirectories so don't change its name here
# the -w y is to silence errors on the visitor_xxx files with the unused
# variable false positive
OPTFLAGS?=-thread -g -w y

OCAMLC=ocamlc$(OPTBIN) $(OCAMLCFLAGS) $(PP) $(INCLUDES)
OCAMLOPT=ocamlopt$(OPTBIN) $(OPTFLAGS) $(PP) $(INCLUDES)
OCAMLLEX=ocamllex #-ml # -ml for debugging lexer, but slightly slower
OCAMLYACC=ocamlyacc -v
OCAMLDEP=ocamldep $(PP)
OCAMLMKTOP=ocamlmktop -g -custom $(INCLUDES) -thread

# can also be set via 'make static'
STATIC= #-ccopt -static

# can also be unset via 'make purebytecode'
BYTECODE_STATIC=-custom

##############################################################################
# Top rules
##############################################################################
all::

##############################################################################
# Generic Literate programming variables
##############################################################################

SYNCFLAGS=-md5sum_in_auxfile -less_marks

SYNCWEB=~/github/syncweb/syncweb $(SYNCFLAGS)
NOWEB=~/github/syncweb/scripts/noweblatex
OCAMLDOC=ocamldoc $(INCLUDES)

PDFLATEX=pdflatex --shell-escape 

lpclean::
	rm -f *.aux *.toc *.log *.brf *.out

##############################################################################
# Developer rules
##############################################################################

#old: otags -no-mli-tags -r  .  but does not work very well
# better to use my own tagger :)
otags:
	echo "you should use stags (in pfff) or ocaml merlin"
distclean::
	rm -f TAGS

DOTCOLORS=green,darkgoldenrod2,cyan,red,magenta,yellow,burlywood1,aquamarine,purple,lightpink,salmon,mediumturquoise,black,slategray3

dot:
	$(OCAMLDOC) -I +threads $(SRC) -dot -dot-reduce \
	   -dot-colors $(DOTCOLORS)
	dot -Tps ocamldoc.out > dot.ps
	mv dot.ps Fig_graph_ml.ps
	ps2pdf Fig_graph_ml.ps
	rm -f Fig_graph_ml.ps

doti:
	$(OCAMLDOC) -I +threads $(SRC:.ml=.mli) -dot
	dot -Tps ocamldoc.out > dot.ps
	mv dot.ps Fig_graph_mli.ps
	ps2pdf Fig_graph_mli.ps
	rm -f Fig_graph_mli.ps

##############################################################################
# Install
##############################################################################

# Installing the .ml can be useful for tools like codegraph or Merlin,
# but if your 'make depend' is wrong and include directories under OPAM,
# then you will possibly get issues with inconcistent definitions because
# make will try to recompile the .ml from OPAM! It would be good to
# sandbox .opam/ with a read-only filesystem like OPAM 2 does when installing
# new packages. In the mean time cp -a ~/.opam/ /tmp to back it up.
install-lib: all all.opt
	ocamlfind install $(OPAMPKG) META lib.cma lib.cmxa *.a *.cmi *.cmt* *.mli *.ml

uninstall-lib::
	ocamlfind remove $(OPAMPKG)

reinstall-lib:
	$(MAKE) uninstall-lib
	$(MAKE) install-lib

##############################################################################
# Generic ocaml rules
##############################################################################

.SUFFIXES: .ml .mli .cmo .cmi .cmx .cmt

.ml.cmo:
	$(OCAMLC)  -c $<
.mli.cmi:
	$(OCAMLC)  -c $<
.ml.cmx:
	$(OCAMLOPT)  -c $<

.ml.mldepend: 
	$(OCAMLC) -i $<

clean::
	rm -f *.cm[ioxa] *.cmt* *.o *.a *.cmxa *.annot
	rm -f *~ .*~ *.exe gmon.out #*#

clean::
	rm -f *.aux *.toc *.log *.brf *.out

distclean::
	rm -f .depend

beforedepend::

# see https://stackoverflow.com/questions/6145041/makefile-filter-out-strings-containing-a-character
FILTER_OUT = $(foreach v,$(2),$(if $(findstring $(1),$(v)),,$(v)))
INCLUDEDIRS2=$(call FILTER_OUT,external, $(INCLUDEDIRS))
INCLUDES2=$(INCLUDEDIRS2:%=-I %)

depend:: beforedepend
	$(OCAMLDEP) $(INCLUDES2) *.mli *.ml > .depend

-include .depend
