##############################################################################
# Variables
##############################################################################

-include ../Makefile.config

LIBNAME=commons_core

SRC=ANSITerminal.ml console.ml \
 int.ml \
 math.ml \
 logger.ml \
 parallel.ml \

INCLUDEDIRS=../commons

OCAMLMKLIB=ocamlc -a
OCAMLMKLIBOPT=ocamlopt -a

-include ../commons/Makefile.common
